import React from "react";
export const places = [
  {
    id: 1,
    name: "Valley of Flowers",
    state: "Uttarakhand",
    status: "open",
    bestTimeToVisit: "June to October",
    image: '/images/img1.jpg',
    description: "A UNESCO World Heritage Site known for its meadows of endemic alpine flowers and rich biodiversity.",
  },
  {
    id: 2,
    name: "Pangi Valley",
    state: "Himachal Pradesh",
    status: "remote",
    bestTimeToVisit: "May to October",
    image: '/images/img1.jpg',
    description: "A secluded valley with breathtaking landscapes and a rich cultural heritage.",
  },
  {
    id: 3,
    name: "Har Ki Dun Valley",
    state: "Uttarakhand",
    status: "open",
    bestTimeToVisit: "April to June, September to December",
    image: '/images/img1.jpg',
    description: "A picturesque valley surrounded by snow-capped peaks, popular among trekkers.",
  },
  {
    id: 4,
    name: "Spiti Valley",
    state: "Himachal Pradesh",
    status: "open",
    bestTimeToVisit: "May to October",
    image: '/images/img1.jpg',
    description: "A high-altitude cold desert valley with stunning landscapes and ancient monasteries.",
  },
  {
    id: 5,
    name: "Chopta Valley",
    state: "Uttarakhand",
    status: "open",
    bestTimeToVisit: "March to June, September to November",
    image: '/images/img1.jpg',
    description: "Known as the 'Mini Switzerland' of India, this valley offers panoramic views of the Himalayas.",
  },
  {
    id: 6,
    name: "Parvati Valley",
    state: "Himachal Pradesh",
    status: "open",
    bestTimeToVisit: "April to October",
    image: '/images/img1.jpg',
    description: "A beautiful valley known for its scenic beauty, hot springs, and vibrant culture.",
  },
  {
    id: 7,
    name: "Nelong Valley",
    state: "Uttarakhand",
    status: "restricted",
    bestTimeToVisit: "May to October",
   image: '/images/img1.jpg',
    description: "A hidden gem near the Indo-Tibetan border, known for its unique landscape and wildlife.",
  },
  {
    id: 8,
    name: "Kinnaur Valley",
    state: "Himachal Pradesh",
    status: "open",
    bestTimeToVisit: "April to October",
    image: '/images/img1.jpg',
    description: "A stunning valley with orchards, picturesque villages, and rich cultural heritage.",
  },
  {
    id: 9,
    name: "Binsar Valley",
    state: "Uttarakhand",
    status: "open",
    bestTimeToVisit: "October to March",
    image: '/images/img1.jpg',
    description: "A serene valley offering panoramic views of the Himalayan peaks and rich flora and fauna.",
  },
  {
    id: 10,
    name: "Barot Valley",
    state: "Himachal Pradesh",
    status: "open",
    bestTimeToVisit: "April to October",
    image: '/images/img1.jpg',
    description: "A hidden gem known for its natural beauty, trout fishing, and adventure activities.",
  },
];
